FROM        1010235_ubuntu
MAINTAINER  wnrhd114@gmail.com

# pyenv virtualenv
RUN         pyenv install 3.6.1
RUN         pyenv virtualenv 3.6.1 app_env

RUN         /root/.pyenv/versions/app_env/bin/pip install uwsgi
RUN         pyenv local app_env
RUN         /root/.pyenv/versions/app_env/bin/pip install -r .requirements/deploy.txt